### ISSUE TITLE
install bug

### ISSUE THREAD

**Issue by SlippyJimmy** [y9c/myneovim.lua#2]
![image](https://user-images.githubusercontent.com/45062658/109579329-a82cf800-7b33-11eb-8b7e-3cbc4ac42fb6.png)

**Comment by y9c** [comment]
Hi @SlippyJimmy , this error is due to the error of  packer package manager. You can exit vim and open a new buffer, then run `:PackerSync` to upgrade all plugins manually. Meanwhile, seem that luajit is not installed in your system. You need to install neovim from source code and install luajit in your PC.
